defaults:
  - teacher: resnet50
  - student: resnet18
  - dataset: train
  - optimizer: adamw
  - criterion: cross_entropy


warmup_epochs: 100
pseudolabeling_epochs: 200
max_weight: 1 
self_train: False
cross_validation: True

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${data_dir}/${dataset.train_path}
  unlabeled_dataset_path: ${data_dir}/${dataset.unlabeled_path}
  train_transform: ${dataset.transform}
  batch_size: 128
  num_workers: 6

data_dir: ${root_dir}/compressed_dataset
root_dir:  ${hydra:runtime.cwd}

hydra:
  run:
    dir: outputs/${hydra.job.override_dirname}
  job:
    chdir: true
  sweep: 
    dir: outputs
    subdir: ${hydra.job.override_dirname}