defaults:
  - teacher: vggnet
  - student: alexnet
  - dataset: train
  - optimizer: adamw
  - criterion: cross_entropy

warmup_epochs: 40
pseudolabeling_epochs: 40
student_epochs: 10
max_weight: 1 
self_train: False
cross_validation: True


rotnet: 
  _target_: models.rotnet.RotNet
rotnet_epochs: 100

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${data_dir}/${dataset.train_path}
  unlabeled_dataset_path: ${data_dir}/${dataset.unlabeled_path}
  train_transform: ${dataset.transform}
  batch_size: 128
  num_workers: 6

test_path: ${data_dir}/${dataset.test_path}

data_dir: ${root_dir}/compressed_dataset
root_dir:  ${hydra:runtime.cwd}
checkpoints_dir: ${root_dir}/checkpoints
checkpoint_path: ${checkpoints_dir}/dataset=train_better,pseudolabeling_epochs=40,student=alexnet,teacher=vggnet,warmup_epochs=40_0teacher_epoch_30.pth

hydra:
  run:
    dir: outputs/${hydra.job.override_dirname}
  job:
    chdir: true
    config:
      override_dirname:
        exclude_keys: 
          - datamodule.batch_size
          - datamodule.num_workers
  sweep: 
    dir: outputs
    subdir: ${hydra.job.override_dirname}